apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog.fullname" . | default "catalog" }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: catalog
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 8080
      protocol: TCP
      name: http
